version: '3.1'

services:
  db:
    image: postgres:13-alpine
    container_name: nest-prisma-postgres
    ports:
      - '5431:5432'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
